# This is the base config override, which keep most of the defaults
# and overrides only whats actually necessary for most users

# This database will store the index of the files, what has been done, etc.
# And is very useful if we want to revert what has been done, and only what has been done.
database: "/config/symlinkerr.sqlite"

logger:
  # Log level DEBUG or INFO, WARN and ERROR are possible but not recommended
  level: INFO

finder:
  directories:
    # Directories where we will delete files and replace them with symlinks
    watch-directories: []
      # - dir: "/data/media/movies"

    # Directories where we will try to find replacements
    # Only files with the exact same size will be eligible.
    # After finding a candidate, the hash of both files will be computed to ensure they
    # are indeed identical (and accessible!)
    # If multiple candidates are found, the top priority will be used (ie. the lowest)
    # If there is still multiple matching candidates, a random one will be chosen
    # It is VERY important those paths are mounted to the same places everywhere
    # (host, containers, etc.), otherwise they won't resolve properly accross apps
    symlink-target-directories: []
      # - dir: "/mnt/remotes/rclone/zurg/__downloads__"
      #   priority: 1
      # - dir: "/mnt/remotes/rclone/zurg/__all__"
      #   priority: 2

    # Symlinks in this folder will be replaced by the content at the target of the symlink
    # Eg. this is the things you actually want to store locally, if you are happy with the content
    # Must obviously NOT be with the watch-directories, otherwise it will replace with a symlink,
    # then replace that symlink with content, etc.
    undo-all-symlinks-directories: []
      # - dir: "/data/media/movies-i-like"

checker:
  # How long to wait after the file has been last modified to replace it
  files-min-age-seconds: 3600

  # Do not try to replace small files, put that to a relatively large value, eg. 50MB or more
  files-min-size-bytes: 52428800

  # Checks that the hash of both files are the same (and that they are indeed readable)
  # Should always be true, unless find-candidates-by is FILENAME and you have reencoded
  # the original files, so they are actually different on disk
  check-hash: true

  # Can be set to false if your files aren't supposed to change but are still pushing
  # fake modification times to the filesystem
  change-in-mtime-invalidates-hash: true

  # Files and folders that shouldn't be visible to the indexer
  # All exclusions are evaluated against the full absolute path of the files
  # Just write regexes in there
  exclusions:
    watch-directories-regexes: []
    symlink-target-directories-regexes: []
    undo-all-symlinks-directories-regexes: []

replacer:
  # Dry run will only log what it would have done, but won't do anything.
  # It will populate the hash cache though, so the next runs will be very fast.
  dry-run: true

  # Permissions to set on files created
  # 99 / 100 is good for Unraid (nobody/users), adjust to your own needs
  chown-uid: 99
  chown-gid: 100
  chmod: 777
