# This database will store the index of the files, what has been done, etc.
# And is very useful if we want to revert what has been done, and only what has been done.
database: "/config/symlinkerr.sqlite"

watcher:
  # How often to check for new files and replace them
  interval-seconds: 86400

  # How often should be recheck files for which we failed to find a match
  # 0 to disable. Use "reset-failures" action so they will be checked again on the next check.
  recheck-failures-interval-seconds: 0

finder:
  # Do not try to replace files too early, as they might still be processing
  files-min-age-seconds: 3600

  # Do not try to replace small files
  files-min-size-bytes: 1048576

directories:
  # Directories where we will delete files
  watch-directories:
    - "/data/media"

  # Directories where we will try to find replacements
  # Only files with the exact same size will be eligible.
  # After finding a candidate, the hash of both files will be computed to ensure they are indeed identical (and accessible!)
  symlink-target-directories:
    - "/mnt/remotes/zurg"

# Files and folders that shouldn't be visible to the indexer
exclusions:
  watch-directories: []
  watch-directories-regexes: []
  symlink-target-directories: []
  symlink-target-directories-regexes: []
