logger:
  level: INFO

watcher:
  interval-seconds: 3600

finder:
  followlinks: false
  find-candidates-by: "SIZE"

  directories:
    watch-directories:
      - dir: "/data/media/movies-tmp"
      - dir: "/data/media/movies"

    symlink-target-directories:
      - dir: "/mnt/remotes/rclone/zurg/__downloads__"
        priority: 1
      - dir: "/mnt/remotes/rclone/zurg/__all__"
        priority: 2

    undo-all-symlinks-directories: []
      # - dir: "/data/media/movies-backupthis"
      # - dir: "/data/media/tv-backupthis"

checker:
  files-min-age-seconds: 0
  change-in-mtime-invalidates-hash: false

replacer:
  dry-run: true
